export default [
  {
    id: 1,
    name: 'BLACK/REFLECTIVE',
    price: 179900,
    desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquam aperiam aspernatur corporis delectus dolorum est excepturi explicabo id molestias natus nesciunt numquam, quibusdam tempore.',
    star: 3,
    review: 98,
  },
  {
    id: 2,
    name: 'WHITE/IT’S ALL RIGHT',
    price: 129900,
    desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquam aperiam aspernatur corporis delectus dolorum est excepturi explicabo',
    star: 4,
    review: 152,
  },
  {
    id: 3,
    name: 'BLACK/SPONGEBOB',
    price: 249900,
    desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquam aperiam aspernatur corporis',
    star: 3,
    review: 59,
  },
  {
    id: 4,
    name: 'WHITE/LEAVES',
    price: 179900,
    desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquam aperiam aspernatur corporis delectus dolorum est excepturi explicabo id molestias natus nesciunt numquam, quibusdam tempore.',
    star: 5,
    review: 87,
  },
  {
    id: 5,
    name: 'BURGUNDY',
    price: 299900,
    desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquam aperiam aspernatur corporis delectus dolorum est excepturi',
    star: 4,
    review: 37,
  },
  {
    id: 6,
    name: 'WHITE/MANHATTAN',
    price: 179900,
    desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquam aperiam aspernatur corporis delectus dolorum est ',
    star: 3,
    review: 134,
  },
  {
    id: 7,
    name: 'WHITE/LOVE',
    price: 129900,
    desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquam aperiam aspernatur corporis delectus',
    star: 4,
    review: 201,
  },
  {
    id: 8,
    name: 'DARK BLUE/PALM TREES',
    price: 249900,
    desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquam aperiam aspernatur corporis delectus dolorum est excepturi explicabo id molestias natus nesciunt',
    star: 3,
    review: 97,
  },
  {
    id: 9,
    name: 'YELLOW/FRUIT',
    price: 249900,
    desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquam aperiam aspernatur corporis delectus dolorum est excepturi explicabo id molestias natus',
    star: 4,
    review: 73,
  },
  {
    id: 10,
    name: 'BEIGE/NASA',
    price: 249900,
    desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquam aperiam aspernatur corporis delectus dolorum est excepturi explicabo id molestias natus nesciunt numquam, quibusdam tempore.',
    star: 4,
    review: 84,
  },
];
